//! build.rs — generate static-payload symbol declarations for bridge/shim.rs.
//!
//! runtime_shim (DC3 port target) 阶段嵌入的 static 资源 (index.html /
//! test.json / ...) 由 build_single.sh 通过 objcopy 转成 payload 对象, 导出
//! `<safe_name>_start` / `<safe_name>_end` 符号. Rust 侧需要 `extern "C"`
//! 引用, 但符号名来自文件名, 不能在源码里写死.
//!
//! build_single.sh 通过环境变量传入:
//!   SHIM_STATIC_N              : 嵌入的 static 文件数 (0..=5)
//!   SHIM_STATIC_<i>_NAME       : 原始文件名 (如 "index.html")
//!   SHIM_STATIC_<i>_START      : objcopy 导出的 _start 符号
//!   SHIM_STATIC_<i>_END        : objcopy 导出的 _end 符号
//!
//! 生成 $OUT_DIR/shim_static_gen.rs, 由 bridge/shim.rs 用 include! 引入.
//! 当 SHIM_STATIC_N 未设置 (普通 `cargo test` / `cargo build`) 时,
//! 生成空表 + N_EMBED_STATIC=0, 保证 `cargo test` 能编译运行.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("shim_static_gen.rs");
    let mut s = String::new();

    let n: usize = env::var("SHIM_STATIC_N")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(0);

    s.push_str(&format!(
        "/// Auto-generated by build.rs (DC3 shim): {} embedded static file(s).\n",
        n
    ));
    s.push_str("/// do not edit by hand.\n");
    s.push_str(&format!("pub const N_EMBED_STATIC: usize = {};\n\n", n));

    for i in 0..n {
        let start = env::var(format!("SHIM_STATIC_{}_START", i)).unwrap_or_default();
        let end = env::var(format!("SHIM_STATIC_{}_END", i)).unwrap_or_default();
        assert!(!start.is_empty() && !end.is_empty(),
            "SHIM_STATIC_{i}_{{START,END}} required", i=i);
        s.push_str(&format!(
            "extern \"C\" {{ pub static {start}: u8; }}\n\
             extern \"C\" {{ pub static {end}: u8; }}\n",
            start = start, end = end
        ));
    }

    s.push_str(
        "/// (name, start, end) 三元组表; 无嵌入时返回空.\n\
         /// 运行期一次性分配 (启动仅一次), 无持续开销.\n\
         pub fn embedded_static_files() -> Vec<(&'static str, *const u8, *const u8)> {\n"
    );
    if n == 0 {
        s.push_str("    Vec::new()\n");
    } else {
        s.push_str("    let mut v = Vec::with_capacity(N_EMBED_STATIC);\n");
        for i in 0..n {
            let name = env::var(format!("SHIM_STATIC_{}_NAME", i)).unwrap_or_default();
            let start = env::var(format!("SHIM_STATIC_{}_START", i)).unwrap_or_default();
            let end = env::var(format!("SHIM_STATIC_{}_END", i)).unwrap_or_default();
            assert!(!name.is_empty(), "SHIM_STATIC_{i}_NAME required", i=i);
            s.push_str(&format!(
                "    v.push((\"{name}\", unsafe {{ &{start} as *const u8 }}, unsafe {{ &{end} as *const u8 }}));\n",
                name = name, start = start, end = end
            ));
        }
        s.push_str("    v\n");
    }
    s.push_str("}\n");

    fs::write(&dest, s).expect("write generated shim file");
    println!("cargo:rerun-if-env-changed=SHIM_STATIC_N");
    for i in 0..n {
        println!("cargo:rerun-if-env-changed=SHIM_STATIC_{i}_NAME");
        println!("cargo:rerun-if-env-changed=SHIM_STATIC_{i}_START");
        println!("cargo:rerun-if-env-changed=SHIM_STATIC_{i}_END");
    }
}
